# Generated by Django 5.2.6 on 2026-01-04 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0002_initial'),
        ('graph', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PARENT_OF', 'Parent Of'), ('SPOUSE_OF', 'Spouse Of')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='families.family')),
                ('from_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relationships', to='graph.person')),
                ('to_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relationships', to='graph.person')),
            ],
            options={
                'db_table': 'graph_relationship',
                'ordering': ['-created_at'],
                'unique_together': {('family', 'from_person', 'to_person', 'type')},
            },
        ),
    ]
