# Generated by Django 5.2.6 on 2026-01-17 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_alter_post_type_postcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='file_attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='post',
            name='voice_message',
            field=models.FileField(blank=True, null=True, upload_to='voice/%Y/%m/%d/'),
        ),
    ]
